#pragma once

#define WORD_MAX 0xffff

#include "service.h"

enum EMisc
{
	MAX_HOST_LENGTH			= 15,
	IP_ADDRESS_LENGTH		= 15,
	LOGIN_MAX_LEN			= 30,
	PASSWD_MAX_LEN			= 16,
	PLAYER_PER_ACCOUNT		= 5,
	ACCOUNT_STATUS_MAX_LEN	= 8,
	CHARACTER_NAME_MAX_LEN	= 24,
	SHOP_SIGN_MAX_LEN		= 32,
	INVENTORY_MAX_NUM		= 180,
	ABILITY_MAX_NUM			= 50,
	EMPIRE_MAX_NUM			= 4,
	BANWORD_MAX_LEN			= 24,
	SMS_MAX_LEN				= 80,
	MOBILE_MAX_LEN			= 32,
	SOCIAL_ID_MAX_LEN		= 18,

	GUILD_NAME_MAX_LEN		= 12,

	SHOP_HOST_ITEM_MAX_NUM	= 80,	
	SHOP_GUEST_ITEM_MAX_NUM = 18,	/* �Խ�Ʈ�� �ִ� ������ ���� */

	SHOP_PRICELIST_MAX_NUM	= 80,	///< ���λ��� �������� ����Ʈ���� ������ ���������� �ִ� ����

	CHAT_MAX_LEN			= 512,

	QUICKSLOT_MAX_NUM		= 36,

	JOURNAL_MAX_NUM			= 2,

	QUERY_MAX_LEN			= 8192,

	FILE_MAX_LEN			= 128,

	PLAYER_EXP_TABLE_MAX	= 120,
	PLAYER_MAX_LEVEL_CONST	= 120,

	GUILD_MAX_LEVEL			= 20,
	MOB_MAX_LEVEL			= 100,

	ATTRIBUTE_MAX_VALUE		= 20,
	CHARACTER_PATH_MAX_NUM	= 64,
	SKILL_MAX_NUM			= 255,
	SKILLBOOK_DELAY_MIN		= 64800,
	SKILLBOOK_DELAY_MAX		= 64800, 
#ifdef __SKILLS_LEVEL_OVER_P__
	SKILL_MAX_LEVEL			= 50,
#else
	SKILL_MAX_LEVEL			= 40,
#endif

	APPLY_NAME_MAX_LEN		= 32,
	EVENT_FLAG_NAME_MAX_LEN = 32,

	MOB_SKILL_MAX_NUM		= 5,

    POINT_MAX_NUM = 255,
	DRAGON_SOUL_BOX_SIZE = 32,
	DRAGON_SOUL_BOX_COLUMN_NUM = 8,
	DRAGON_SOUL_BOX_ROW_NUM = DRAGON_SOUL_BOX_SIZE / DRAGON_SOUL_BOX_COLUMN_NUM,
	DRAGON_SOUL_REFINE_GRID_SIZE = 15,
	MAX_AMOUNT_OF_MALL_BONUS	= 20,

	//LIMIT_GOLD
	GOLD_MAX = 2000000000,

	MAX_PASSPOD = 8 ,

		
	//END_LIMIT_GOLD

	SHOP_TAB_NAME_MAX = 32,
	SHOP_TAB_COUNT_MAX = 3,

	BELT_INVENTORY_SLOT_WIDTH = 4,
	BELT_INVENTORY_SLOT_HEIGHT= 4,

	BELT_INVENTORY_SLOT_COUNT = BELT_INVENTORY_SLOT_WIDTH * BELT_INVENTORY_SLOT_HEIGHT,
};

/*
	Character item-slot layout (window_type == INVENTORY), see EMisc2 below for the actual
	constants. Every reserved block is intentional headroom for future growth of that one
	category - if you need to add slots to a category, take them from ITS OWN reserve first,
	so the categories after it don't shift again.

	[0, INVENTORY_MAX_NUM)                                    base bag inventory
	[EQUIPMENT_SLOT_START, EQUIPMENT_SLOT_END)                worn equipment (see item_length.h EWearPositions)
	[EQUIPMENT_RESERVED_START, +EQUIPMENT_RESERVED_COUNT)      reserved: future equip/costume slots
	[DRAGON_SOUL_EQUIP_SLOT_START, DRAGON_SOUL_EQUIP_SLOT_END) active dragon soul decks
	[DRAGON_SOUL_EQUIP_RESERVED_SLOT_START, .._END)            reserved: a future 3rd dragon soul deck
	[BELT_INVENTORY_SLOT_START, BELT_INVENTORY_SLOT_END)       belt inventory (4x4)
	[BELT_INVENTORY_RESERVED_START, +..._COUNT)                reserved: a future larger belt grid
	[SKILL_BOOK_INVENTORY_SLOT_START, .._END)                  skill book tab (WJ_SPLIT_INVENTORY_SYSTEM)
	[SKILL_BOOK_INVENTORY_RESERVED_START, +..._COUNT)          reserved: +1 page
	[UPGRADE_ITEMS_INVENTORY_SLOT_START, .._END)               upgrade-items tab
	[UPGRADE_ITEMS_INVENTORY_RESERVED_START, +..._COUNT)       reserved: +1 page
	[STONE_INVENTORY_SLOT_START, .._END)                       stone tab
	[STONE_INVENTORY_RESERVED_START, +..._COUNT)               reserved: +1 page
	[SANDIK_INVENTORY_SLOT_START, SANDIK_INVENTORY_SLOT_END)   chest tab (last - no reserve needed,
	                                                            growing it never shifts anything else)
	                                                            = INVENTORY_AND_EQUIP_SLOT_MAX
*/

enum EMatrixCard
{
	MATRIX_CODE_MAX_LEN		= 192,
	MATRIX_ANSWER_MAX_LEN	= 8,
};

enum EDragonSoulDeckType
{
	DRAGON_SOUL_DECK_0,
	DRAGON_SOUL_DECK_1,
	DRAGON_SOUL_DECK_MAX_NUM = 2,

	DRAGON_SOUL_DECK_RESERVED_MAX_NUM = 3,	// NOTE: �߿�! ���� ��������� ������, 3������ �з��� ���� �� ��. DS DECK�� �ø� ��� �ݵ�� �� ����ŭ RESERVED���� �����ؾ� ��!
};

enum ESex
{
	SEX_MALE,
	SEX_FEMALE
};

enum EDirection
{
	DIR_NORTH,
	DIR_NORTHEAST,
	DIR_EAST,
	DIR_SOUTHEAST,
	DIR_SOUTH,
	DIR_SOUTHWEST,
	DIR_WEST,
	DIR_NORTHWEST,
	DIR_MAX_NUM
};

#define ABILITY_MAX_LEVEL	10  /* ��� �ִ� ���� */

enum EAbilityDifficulty
{
	DIFFICULTY_EASY,
	DIFFICULTY_NORMAL,
	DIFFICULTY_HARD,
	DIFFICULTY_VERY_HARD,
	DIFFICULTY_NUM_TYPES
};

enum EAbilityCategory
{
	CATEGORY_PHYSICAL,	/* ��ü�� �����Ƽ */
	CATEGORY_MENTAL,	/* ������ �����Ƽ */
	CATEGORY_ATTRIBUTE,	/* �ɷ� �����Ƽ */
	CATEGORY_NUM_TYPES
};

enum EJobs
{
	JOB_WARRIOR,
	JOB_ASSASSIN,
	JOB_SURA,
	JOB_SHAMAN,
	JOB_MAX_NUM
};

enum ESkillGroups
{
	SKILL_GROUP_MAX_NUM = 2,
};

enum ERaceFlags
{
	RACE_FLAG_ANIMAL	= (1 << 0),
	RACE_FLAG_UNDEAD	= (1 << 1),
	RACE_FLAG_DEVIL		= (1 << 2),
	RACE_FLAG_HUMAN		= (1 << 3),
	RACE_FLAG_ORC		= (1 << 4),
	RACE_FLAG_MILGYO	= (1 << 5),
	RACE_FLAG_INSECT	= (1 << 6),
	RACE_FLAG_FIRE		= (1 << 7),
	RACE_FLAG_ICE		= (1 << 8),
	RACE_FLAG_DESERT	= (1 << 9),
	RACE_FLAG_TREE		= (1 << 10),
	RACE_FLAG_ATT_ELEC	= (1 << 11),
	RACE_FLAG_ATT_FIRE	= (1 << 12),
	RACE_FLAG_ATT_ICE	= (1 << 13),
	RACE_FLAG_ATT_WIND	= (1 << 14),
	RACE_FLAG_ATT_EARTH	= (1 << 15),
	RACE_FLAG_ATT_DARK	= (1 << 16),
};

enum ELoads
{
	LOAD_NONE,
	LOAD_LIGHT,
	LOAD_NORMAL,
	LOAD_HEAVY,
	LOAD_MASSIVE
};

enum
{
	QUICKSLOT_TYPE_NONE,
	QUICKSLOT_TYPE_ITEM,
	QUICKSLOT_TYPE_SKILL,
	QUICKSLOT_TYPE_COMMAND,
	QUICKSLOT_TYPE_MAX_NUM,
};

enum EParts
{
	PART_MAIN,
	PART_WEAPON,
	PART_HEAD,
	PART_HAIR,

	PART_MAX_NUM,
	PART_WEAPON_SUB,
};

enum EChatType
{
	CHAT_TYPE_TALKING,	
	CHAT_TYPE_INFO,	
	CHAT_TYPE_NOTICE,	
	CHAT_TYPE_PARTY,	
	CHAT_TYPE_GUILD,	
	CHAT_TYPE_COMMAND,	
	CHAT_TYPE_SHOUT,	
	CHAT_TYPE_WHISPER,
	CHAT_TYPE_BIG_NOTICE,
#if defined(ENABLE_CHATTING_WINDOW_RENEWAL)
	CHAT_TYPE_EXP_INFO,
	CHAT_TYPE_ITEM_INFO,
	CHAT_TYPE_MONEY_INFO,
#endif
	CHAT_TYPE_MONARCH_NOTICE,	// unused server-only tag, no client-side counterpart - kept after the wire-matched block above so it can't shift EXP/ITEM/MONEY_INFO's values out of sync with the client enum again
	CHAT_TYPE_MAX_NUM
};

enum EWhisperType
{
	WHISPER_TYPE_NORMAL		= 0,
	WHISPER_TYPE_NOT_EXIST		= 1,
	WHISPER_TYPE_TARGET_BLOCKED	= 2,
	WHISPER_TYPE_SENDER_BLOCKED	= 3,
	WHISPER_TYPE_ERROR		= 4,
	WHISPER_TYPE_GM			= 5,
	WHISPER_TYPE_SYSTEM		= 0xFF
};

enum ECharacterPosition
{
	POSITION_GENERAL,
	POSITION_BATTLE,
	POSITION_DYING,
	POSITION_SITTING_CHAIR,
	POSITION_SITTING_GROUND,
	POSITION_INTRO,
	POSITION_MAX_NUM
};

enum EGMLevels
{
	GM_PLAYER,
	GM_LOW_WIZARD,
	GM_WIZARD,
	GM_HIGH_WIZARD,
	GM_GOD,
	GM_IMPLEMENTOR
};

enum EMobRank
{
	MOB_RANK_PAWN,
	MOB_RANK_S_PAWN,
	MOB_RANK_KNIGHT,
	MOB_RANK_S_KNIGHT,
	MOB_RANK_BOSS,
	MOB_RANK_KING,
	MOB_RANK_MAX_NUM
};

enum ECharType
{
	CHAR_TYPE_MONSTER,
	CHAR_TYPE_NPC,
	CHAR_TYPE_STONE,
	CHAR_TYPE_WARP,
	CHAR_TYPE_DOOR,
	CHAR_TYPE_BUILDING,
	CHAR_TYPE_PC,
	CHAR_TYPE_POLYMORPH_PC,
	CHAR_TYPE_HORSE,
	CHAR_TYPE_GOTO
};

enum EBattleType
{
	BATTLE_TYPE_MELEE,
	BATTLE_TYPE_RANGE,
	BATTLE_TYPE_MAGIC,
	BATTLE_TYPE_SPECIAL,
	BATTLE_TYPE_POWER,
	BATTLE_TYPE_TANKER,
	BATTLE_TYPE_SUPER_POWER,
	BATTLE_TYPE_SUPER_TANKER,
	BATTLE_TYPE_MAX_NUM
};

enum EApplyTypes
{
	APPLY_NONE,			// 0
	APPLY_MAX_HP,		// 1
	APPLY_MAX_SP,		// 2
	APPLY_CON,			// 3
	APPLY_INT,			// 4
	APPLY_STR,			// 5
	APPLY_DEX,			// 6
	APPLY_ATT_SPEED,	// 7
	APPLY_MOV_SPEED,	// 8
	APPLY_CAST_SPEED,	// 9
	APPLY_HP_REGEN,		// 10
	APPLY_SP_REGEN,		// 11
	APPLY_POISON_PCT,	// 12
	APPLY_STUN_PCT,		// 13
	APPLY_SLOW_PCT,		// 14
	APPLY_CRITICAL_PCT,		// 15
	APPLY_PENETRATE_PCT,	// 16
	APPLY_ATTBONUS_HUMAN,	// 17
	APPLY_ATTBONUS_ANIMAL,	// 18
	APPLY_ATTBONUS_ORC,		// 19
	APPLY_ATTBONUS_MILGYO,	// 20
	APPLY_ATTBONUS_UNDEAD,	// 21
	APPLY_ATTBONUS_DEVIL,	// 22
	APPLY_STEAL_HP,			// 23
	APPLY_STEAL_SP,			// 24
	APPLY_MANA_BURN_PCT,	// 25
	APPLY_DAMAGE_SP_RECOVER,	// 26
	APPLY_BLOCK,			// 27
	APPLY_DODGE,			// 28
	APPLY_RESIST_SWORD,		// 29
	APPLY_RESIST_TWOHAND,	// 30
	APPLY_RESIST_DAGGER,	// 31
	APPLY_RESIST_BELL,		// 32
	APPLY_RESIST_FAN,		// 33
	APPLY_RESIST_BOW,		// 34
	APPLY_RESIST_FIRE,		// 35
	APPLY_RESIST_ELEC,		// 36
	APPLY_RESIST_MAGIC,		// 37
	APPLY_RESIST_WIND,		// 38
	APPLY_REFLECT_MELEE,	// 39
	APPLY_REFLECT_CURSE,	// 40
	APPLY_POISON_REDUCE,	// 41
	APPLY_KILL_SP_RECOVER,	// 42
	APPLY_EXP_DOUBLE_BONUS,	// 43
	APPLY_GOLD_DOUBLE_BONUS,	// 44
	APPLY_ITEM_DROP_BONUS,	// 45
	APPLY_POTION_BONUS,		// 46
	APPLY_KILL_HP_RECOVER,	// 47
	APPLY_IMMUNE_STUN,		// 48
	APPLY_IMMUNE_SLOW,		// 49
	APPLY_IMMUNE_FALL,		// 50
	APPLY_SKILL,			// 51
	APPLY_BOW_DISTANCE,		// 52
	APPLY_ATT_GRADE_BONUS,	// 53
	APPLY_DEF_GRADE_BONUS,	// 54
	APPLY_MAGIC_ATT_GRADE,	// 55
	APPLY_MAGIC_DEF_GRADE,	// 56
	APPLY_CURSE_PCT,		// 57
	APPLY_MAX_STAMINA,		// 58
	APPLY_ATTBONUS_WARRIOR,	// 59
	APPLY_ATTBONUS_ASSASSIN,	// 60
	APPLY_ATTBONUS_SURA,	// 61
	APPLY_ATTBONUS_SHAMAN,	// 62
	APPLY_ATTBONUS_MONSTER,	// 63
	APPLY_MALL_ATTBONUS,			// 64 ���ݷ� +x%
	APPLY_MALL_DEFBONUS,			// 65 ���� +x%
	APPLY_MALL_EXPBONUS,			// 66 ����ġ +x%
	APPLY_MALL_ITEMBONUS,			// 67 ������ ����� x/10��
	APPLY_MALL_GOLDBONUS,			// 68 �� ����� x/10��
	APPLY_MAX_HP_PCT,				// 69 �ִ� ������ +x%
	APPLY_MAX_SP_PCT,				// 70 �ִ� ���ŷ� +x%
	APPLY_SKILL_DAMAGE_BONUS,		// 71 ��ų ������ * (100+x)%
	APPLY_NORMAL_HIT_DAMAGE_BONUS,	// 72 ��Ÿ ������ * (100+x)%
	APPLY_SKILL_DEFEND_BONUS,		// 73 ��ų ������ ��� * (100-x)%
	APPLY_NORMAL_HIT_DEFEND_BONUS,	// 74 ��Ÿ ������ ��� * (100-x)%
	APPLY_PC_BANG_EXP_BONUS,		// 75 PC�� ������ EXP ���ʽ�
	APPLY_PC_BANG_DROP_BONUS,		// 76 PC�� ������ ����� ���ʽ�

	APPLY_EXTRACT_HP_PCT,			// 77 ���� HP �Ҹ�

	APPLY_RESIST_WARRIOR,			// 78 ���翡�� ����
	APPLY_RESIST_ASSASSIN,			// 79 �ڰ����� ����
	APPLY_RESIST_SURA,				// 80 ���󿡰� ����
	APPLY_RESIST_SHAMAN,			// 81 ���翡�� ����
	APPLY_ENERGY,					// 82 ���
	APPLY_DEF_GRADE,				// 83 ����. DEF_GRADE_BONUS�� Ŭ�󿡼� �ι�� �������� �ǵ��� ����(...)�� �ִ�.
	APPLY_COSTUME_ATTR_BONUS,		// 84 �ڽ�Ƭ �����ۿ� ���� �Ӽ�ġ ���ʽ�
	APPLY_MAGIC_ATTBONUS_PER,		// 85 ���� ���ݷ� +x%
	APPLY_MELEE_MAGIC_ATTBONUS_PER,			// 86 ���� + �и� ���ݷ� +x%
	
	APPLY_RESIST_ICE,		// 87 �ñ� ����
	APPLY_RESIST_EARTH,		// 88 ���� ����
	APPLY_RESIST_DARK,		// 89 ��� ����

	APPLY_ANTI_CRITICAL_PCT,	//90 ũ��Ƽ�� ����
	APPLY_ANTI_PENETRATE_PCT,	//91 ����Ÿ�� ����


	MAX_APPLY_NUM,              // 
};

enum EOnClickEvents
{
	ON_CLICK_NONE,
	ON_CLICK_SHOP,
	ON_CLICK_TALK,
	ON_CLICK_MAX_NUM
};

enum EOnIdleEvents
{
	ON_IDLE_NONE,
	ON_IDLE_GENERAL,
	ON_IDLE_MAX_NUM
};

#ifdef ENABLE_SWITCHBOT
enum ESwitchbotValues
{
	SWITCHBOT_SLOT_COUNT = 5,
	SWITCHBOT_ALTERNATIVE_COUNT = 2,
	SWITCHBOT_ITEM_AMOUNT = 1,		// consumed once per 0.2s reroll attempt (always 1, from whichever vnum below is available)
};

// Any one of these vnums is accepted as the switching item; the first one the player has is consumed.
const DWORD c_arSwitchbotItems[3] =
{
	39028,
	71084,
	76014,
};
#endif

#ifdef ENABLE_OFFLINESHOP_SYSTEM
enum EOfflineShopValues
{
	SHOP_FEE					= 5,				// % commission taken on each sale
	SHOP_TIME_CREATE			= 60*60*24,			// base open duration: 24h
	SHOP_TIME_CREATE_PREMIUM	= 60*60*24*3,		// premium (AFFECT_DECORATION active) open duration: 72h
	SHOP_MAX_TIME				= 60*60*24*3,		// max extendable duration
	SHOP_MAX_TIME_PREMIUM		= 60*60*24*14,
	SHOP_TIME_ADD_TIME			= 60*60*24,			// one "extend time" purchase grants this much
	SHOP_TIME_ADD_TIME_PREMIUM	= 60*60*24*3,
	SHOP_EXPAND_SLOT_PRICE		= 500000,			// gold cost for the pay-with-gold alternative to the 72319-item slot unlock
};
// Bit 63 of TOfflineShop::slotflag (player.player.shop_flag) - only bits 0-39 are ever
// used for the 40 extra-slot unlocks, so this rides the same already-persisted,
// already-DB-fanned-out-to-every-core field for free instead of needing a new column/
// wire struct field of its own. Declared outside EOfflineShopValues since an enum's
// underlying type can't portably hold a 64-bit value.
static const unsigned long long SHOP_LOCKED_FLAG = 1ULL << 63;
#ifdef ENABLE_SHOP_SEARCH_SYSTEM
enum { SHOP_SEARCH_PAGE_SIZE = 50 };
#endif
#endif

enum EWindows
{
	RESERVED_WINDOW,
	INVENTORY,
	EQUIPMENT,
	SAFEBOX,
	MALL,
	DRAGON_SOUL_INVENTORY,
	BELT_INVENTORY,
#ifdef ENABLE_SWITCHBOT
	SWITCHBOT,
#endif
	GROUND
};

enum EMobSizes
{
	MOBSIZE_RESERVED,
	MOBSIZE_SMALL,
	MOBSIZE_MEDIUM,
	MOBSIZE_BIG
};

enum EAIFlags
{
	AIFLAG_AGGRESSIVE	= (1 << 0),
	AIFLAG_NOMOVE	= (1 << 1),
	AIFLAG_COWARD	= (1 << 2),
	AIFLAG_NOATTACKSHINSU	= (1 << 3),
	AIFLAG_NOATTACKJINNO	= (1 << 4),
	AIFLAG_NOATTACKCHUNJO	= (1 << 5),
	AIFLAG_ATTACKMOB = (1 << 6 ),
	AIFLAG_BERSERK	= (1 << 7),
	AIFLAG_STONESKIN	= (1 << 8),
	AIFLAG_GODSPEED	= (1 << 9),
	AIFLAG_DEATHBLOW	= (1 << 10),
	AIFLAG_REVIVE		= (1 << 11),
};

enum EMobStatType
{
	MOB_STATTYPE_POWER,
	MOB_STATTYPE_TANKER,
	MOB_STATTYPE_SUPER_POWER,
	MOB_STATTYPE_SUPER_TANKER,
	MOB_STATTYPE_RANGE,
	MOB_STATTYPE_MAGIC,
	MOB_STATTYPE_MAX_NUM
};

enum EImmuneFlags
{
	IMMUNE_STUN		= (1 << 0),
	IMMUNE_SLOW		= (1 << 1),
	IMMUNE_FALL		= (1 << 2),
	IMMUNE_CURSE	= (1 << 3),
	IMMUNE_POISON	= (1 << 4),
	IMMUNE_TERROR	= (1 << 5),
	IMMUNE_REFLECT	= (1 << 6),
};

enum EMobEnchants
{
	MOB_ENCHANT_CURSE,
	MOB_ENCHANT_SLOW,
	MOB_ENCHANT_POISON,
	MOB_ENCHANT_STUN,
	MOB_ENCHANT_CRITICAL,
	MOB_ENCHANT_PENETRATE,
	MOB_ENCHANTS_MAX_NUM
};

enum EMobResists
{
	MOB_RESIST_SWORD,
	MOB_RESIST_TWOHAND,
	MOB_RESIST_DAGGER,
	MOB_RESIST_BELL,
	MOB_RESIST_FAN,
	MOB_RESIST_BOW,
	MOB_RESIST_FIRE,
	MOB_RESIST_ELECT,
	MOB_RESIST_MAGIC,
	MOB_RESIST_WIND,
	MOB_RESIST_POISON,
	MOB_RESISTS_MAX_NUM
};

enum
{
	SKILL_ATTR_TYPE_NORMAL = 1,
	SKILL_ATTR_TYPE_MELEE,
	SKILL_ATTR_TYPE_RANGE,
	SKILL_ATTR_TYPE_MAGIC
		/*
		   SKILL_ATTR_TYPE_FIRE,
		   SKILL_ATTR_TYPE_ICE,
		   SKILL_ATTR_TYPE_ELEC,
		   SKILL_ATTR_TYPE_DARK,
		   */
};

enum
{
	SKILL_NORMAL,
	SKILL_MASTER,
	SKILL_GRAND_MASTER,
	SKILL_PERFECT_MASTER,
#ifdef __SKILLS_LEVEL_OVER_P__
	SKILL_SAGE_MASTER,
#endif
};

enum EGuildWarType
{
	GUILD_WAR_TYPE_FIELD,
	GUILD_WAR_TYPE_BATTLE,
	GUILD_WAR_TYPE_FLAG,
	GUILD_WAR_TYPE_MAX_NUM
};

enum EGuildWarState
{
	GUILD_WAR_NONE,
	GUILD_WAR_SEND_DECLARE,
	GUILD_WAR_REFUSE,
	GUILD_WAR_RECV_DECLARE,
	GUILD_WAR_WAIT_START,
	GUILD_WAR_CANCEL,
	GUILD_WAR_ON_WAR,
	GUILD_WAR_END,
	GUILD_WAR_OVER,
	GUILD_WAR_RESERVE,

	GUILD_WAR_DURATION = 30*60, // 1�ð�
	GUILD_WAR_WIN_POINT = 1000,
	GUILD_WAR_LADDER_HALF_PENALTY_TIME = 12*60*60,
};

enum EAttributeSet 
{            
	ATTRIBUTE_SET_WEAPON,
	ATTRIBUTE_SET_BODY, 
	ATTRIBUTE_SET_WRIST, 
	ATTRIBUTE_SET_FOOTS,
	ATTRIBUTE_SET_NECK,
	ATTRIBUTE_SET_HEAD,
	ATTRIBUTE_SET_SHIELD,
	ATTRIBUTE_SET_EAR,
#if defined(__COSTUME_SYSTEM__)
	ATTRIBUTE_SET_COSTUME_BODY,
	ATTRIBUTE_SET_COSTUME_HAIR,
#if defined(__WEAPON_COSTUME_SYSTEM__)
	ATTRIBUTE_SET_COSTUME_WEAPON,
#endif
#endif
	ATTRIBUTE_SET_MAX_NUM
};  

enum EPrivType
{
	PRIV_NONE,
	PRIV_ITEM_DROP,
	PRIV_GOLD_DROP,
	PRIV_GOLD10_DROP,
	PRIV_EXP_PCT,
	MAX_PRIV_NUM,
};

enum EMoneyLogType
{
	MONEY_LOG_RESERVED,
	MONEY_LOG_MONSTER,
	MONEY_LOG_SHOP,
	MONEY_LOG_REFINE,
	MONEY_LOG_QUEST,
	MONEY_LOG_GUILD,
	MONEY_LOG_MISC,
	MONEY_LOG_MONSTER_KILL,
	MONEY_LOG_DROP,
	MONEY_LOG_TYPE_MAX_NUM,
};

enum EPremiumTypes
{
	PREMIUM_EXP,		
	PREMIUM_ITEM,		
	PREMIUM_SAFEBOX,	
	PREMIUM_AUTOLOOT,	
	PREMIUM_FISH_MIND,	
	PREMIUM_MARRIAGE_FAST,
	PREMIUM_GOLD,		
	PREMIUM_MAX_NUM = 9
};

enum SPECIAL_EFFECT
{
	SE_NONE,

	SE_HPUP_RED,
	SE_SPUP_BLUE,
	SE_SPEEDUP_GREEN,
	SE_DXUP_PURPLE,
	SE_CRITICAL,
	SE_PENETRATE,
	SE_BLOCK,
	SE_DODGE,
	SE_CHINA_FIREWORK,
	SE_SPIN_TOP,
	SE_SUCCESS,
	SE_FAIL,
	SE_FR_SUCCESS,
	SE_LEVELUP_ON_14_FOR_GERMANY,
	SE_LEVELUP_UNDER_15_FOR_GERMANY,
	SE_PERCENT_DAMAGE1,
	SE_PERCENT_DAMAGE2,
	SE_PERCENT_DAMAGE3,

	SE_AUTO_HPUP,
	SE_AUTO_SPUP,

	SE_EQUIP_RAMADAN_RING,		
	SE_EQUIP_HALLOWEEN_CANDY,		
	SE_EQUIP_HAPPINESS_RING,		
	SE_EQUIP_LOVE_PENDANT,		
} ;

#include "item_length.h"

enum EMisc2
{
	EQUIPMENT_SLOT_START = INVENTORY_MAX_NUM,
	EQUIPMENT_SLOT_COUNT = WEAR_POSITION_COUNT,
	EQUIPMENT_SLOT_END = EQUIPMENT_SLOT_START + EQUIPMENT_SLOT_COUNT,

	EQUIPMENT_RING_SLOT_START = EQUIPMENT_SLOT_START + WEAR_RING1,
	EQUIPMENT_COSTUME_SLOT_START = EQUIPMENT_SLOT_START + WEAR_COSTUME_BODY,

	// Reserved for future equipment/costume slot additions - take from here first,
	// don't grow EQUIPMENT_SLOT_COUNT itself (that would shift every range below again).
	EQUIPMENT_RESERVED_START = EQUIPMENT_SLOT_END,
	EQUIPMENT_RESERVED_COUNT = 10,

	DRAGON_SOUL_EQUIP_SLOT_START = EQUIPMENT_RESERVED_START + EQUIPMENT_RESERVED_COUNT,
	DRAGON_SOUL_EQUIP_SLOT_END = DRAGON_SOUL_EQUIP_SLOT_START + (DS_SLOT_MAX * DRAGON_SOUL_DECK_MAX_NUM),

	// Reserved for a future 3rd dragon soul deck (already-intentional headroom, now named).
	DRAGON_SOUL_EQUIP_RESERVED_SLOT_START = DRAGON_SOUL_EQUIP_SLOT_END,
	DRAGON_SOUL_EQUIP_RESERVED_SLOT_END = DRAGON_SOUL_EQUIP_RESERVED_SLOT_START + (DS_SLOT_MAX * DRAGON_SOUL_DECK_RESERVED_MAX_NUM),

	BELT_INVENTORY_SLOT_START = DRAGON_SOUL_EQUIP_RESERVED_SLOT_END,
	BELT_INVENTORY_SLOT_END = BELT_INVENTORY_SLOT_START + BELT_INVENTORY_SLOT_COUNT,

	// Reserved for a future larger belt grid.
	BELT_INVENTORY_RESERVED_START = BELT_INVENTORY_SLOT_END,
	BELT_INVENTORY_RESERVED_COUNT = BELT_INVENTORY_SLOT_COUNT,

	// WJ_SPLIT_INVENTORY_SYSTEM: dedicated tabs for skill books / development items / stones / chests,
	// laid out as 4 contiguous sub-ranges of the INVENTORY window. Each (except the last, Sandik)
	// has its own named reserved block right after it - grow into that first instead of shifting
	// every category that follows.
	SKILL_BOOK_INVENTORY_SLOT_COUNT = 135,
	SKILL_BOOK_INVENTORY_SLOT_START = BELT_INVENTORY_RESERVED_START + BELT_INVENTORY_RESERVED_COUNT,
	SKILL_BOOK_INVENTORY_SLOT_END = SKILL_BOOK_INVENTORY_SLOT_START + SKILL_BOOK_INVENTORY_SLOT_COUNT,
	SKILL_BOOK_INVENTORY_RESERVED_START = SKILL_BOOK_INVENTORY_SLOT_END,
	SKILL_BOOK_INVENTORY_RESERVED_COUNT = 45,

	UPGRADE_ITEMS_INVENTORY_SLOT_COUNT = 135,
	UPGRADE_ITEMS_INVENTORY_SLOT_START = SKILL_BOOK_INVENTORY_RESERVED_START + SKILL_BOOK_INVENTORY_RESERVED_COUNT,
	UPGRADE_ITEMS_INVENTORY_SLOT_END = UPGRADE_ITEMS_INVENTORY_SLOT_START + UPGRADE_ITEMS_INVENTORY_SLOT_COUNT,
	UPGRADE_ITEMS_INVENTORY_RESERVED_START = UPGRADE_ITEMS_INVENTORY_SLOT_END,
	UPGRADE_ITEMS_INVENTORY_RESERVED_COUNT = 45,

	STONE_INVENTORY_SLOT_COUNT = 135,
	STONE_INVENTORY_SLOT_START = UPGRADE_ITEMS_INVENTORY_RESERVED_START + UPGRADE_ITEMS_INVENTORY_RESERVED_COUNT,
	STONE_INVENTORY_SLOT_END = STONE_INVENTORY_SLOT_START + STONE_INVENTORY_SLOT_COUNT,
	STONE_INVENTORY_RESERVED_START = STONE_INVENTORY_SLOT_END,
	STONE_INVENTORY_RESERVED_COUNT = 45,

	SANDIK_INVENTORY_SLOT_COUNT = 135,
	SANDIK_INVENTORY_SLOT_START = STONE_INVENTORY_RESERVED_START + STONE_INVENTORY_RESERVED_COUNT,
	SANDIK_INVENTORY_SLOT_END = SANDIK_INVENTORY_SLOT_START + SANDIK_INVENTORY_SLOT_COUNT,
	// Sandik is last - it can grow freely without a reserve, nothing else follows it.

	INVENTORY_AND_EQUIP_SLOT_MAX = SANDIK_INVENTORY_SLOT_END,
};

#pragma pack(push, 1)

typedef struct SItemPos
{
	BYTE window_type;
	WORD cell;
    SItemPos ()
    {
        window_type = INVENTORY;
		cell = WORD_MAX;
    }

	SItemPos (BYTE _window_type, WORD _cell)
    {
        window_type = _window_type;
        cell = _cell;
    }

	bool IsValidItemPosition() const
	{
		switch (window_type)
		{
		case RESERVED_WINDOW:
			return false;
		case INVENTORY:
		case EQUIPMENT:
		case BELT_INVENTORY:
			return cell < INVENTORY_AND_EQUIP_SLOT_MAX;
		case DRAGON_SOUL_INVENTORY:
			return cell < (DRAGON_SOUL_INVENTORY_MAX_NUM);
#ifdef ENABLE_SWITCHBOT
		case SWITCHBOT:
			return cell < SWITCHBOT_SLOT_COUNT;
#endif
		case SAFEBOX:
		case MALL:
			return false;
		default:
			return false;
		}
		return false;
	}

	bool IsSamePosition(const SItemPos & other) const // ItemMove dupe exploit fix
	{
		return *this==other
			|| ((INVENTORY == window_type || EQUIPMENT == window_type)
				&& (INVENTORY == other.window_type || EQUIPMENT == other.window_type)
				&& cell == other.cell);
	}

	bool IsEquipPosition() const
	{
		return ((INVENTORY == window_type || EQUIPMENT == window_type) && cell >= EQUIPMENT_SLOT_START && cell < EQUIPMENT_SLOT_END)
			|| IsDragonSoulEquipPosition();
	}

	bool IsDragonSoulEquipPosition() const
	{
		return (DRAGON_SOUL_EQUIP_SLOT_START <= cell) && (DRAGON_SOUL_EQUIP_SLOT_END > cell);
	}

	bool IsBeltInventoryPosition() const
	{
		return (BELT_INVENTORY_SLOT_START <= cell) && (BELT_INVENTORY_SLOT_END > cell);
	}

	bool IsDefaultInventoryPosition() const
	{
		return INVENTORY == window_type && cell < INVENTORY_MAX_NUM;
	}

	bool IsSkillBookInventoryPosition() const
	{
		return (SKILL_BOOK_INVENTORY_SLOT_START <= cell) && (SKILL_BOOK_INVENTORY_SLOT_END > cell);
	}

	bool IsUpgradeItemsInventoryPosition() const
	{
		return (UPGRADE_ITEMS_INVENTORY_SLOT_START <= cell) && (UPGRADE_ITEMS_INVENTORY_SLOT_END > cell);
	}

	bool IsStoneInventoryPosition() const
	{
		return (STONE_INVENTORY_SLOT_START <= cell) && (STONE_INVENTORY_SLOT_END > cell);
	}

	bool IsSandikInventoryPosition() const
	{
		return (SANDIK_INVENTORY_SLOT_START <= cell) && (SANDIK_INVENTORY_SLOT_END > cell);
	}

#ifdef ENABLE_SWITCHBOT
	bool IsSwitchbotPosition() const
	{
		return SWITCHBOT == window_type && cell < SWITCHBOT_SLOT_COUNT;
	}
#endif

	bool operator==(const struct SItemPos& rhs) const
	{
		return (window_type == rhs.window_type) && (cell == rhs.cell);
	}
	bool operator<(const struct SItemPos& rhs) const
	{
		return (window_type < rhs.window_type) || ((window_type == rhs.window_type) && (cell < rhs.cell));
	}
} TItemPos;

const TItemPos NPOS (RESERVED_WINDOW, WORD_MAX);

typedef enum
{
	SHOP_COIN_TYPE_GOLD, // DEFAULT VALUE
	SHOP_COIN_TYPE_SECONDARY_COIN,
} EShopCoinType;

#pragma pack(pop)
